# Bitcoin Network Ports - Chain-specific configurations

[bitcoin.regtest.node1]
rpc = 18332
p2p = 18333
datadir = "bitcoind"

[bitcoin.regtest.node2] 
rpc = 18444
p2p = 18450
datadir = "bitcoind2"

[bitcoin.testnet4.node1]
rpc = 48330
p2p = 48340
datadir = "bitcoind"

[bitcoin.testnet4.node2] 
rpc = 48350
p2p = 48360
datadir = "bitcoind2"

[bitcoin.signet.node1]
rpc = 38330
p2p = 38340
datadir = "bitcoind"

[bitcoin.signet.node2] 
rpc = 38350
p2p = 38360
datadir = "bitcoind2"

# Nostr Relay Ports
[nostr]
strfry1 = 7777
strfry2 = 7778

# TX Relay Server Ports  
[txrelay]
server1 = 7779
server2 = 7780

# Operational settings
[timeouts]
bitcoin_rpc = 60
strfry_ready = 300
strfry_build = 600